const candidatesData = [
  {
    id: 1,
    candidateName: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "+1 (555) 123-4567",
    appliedJob: "Software Engineer",
    appliedDate: "2024-01-15",
    cvMatchPercent: 92,
    interviewStatus: "Completed",
    aiScore: 88,
    recommendation: "Strong Hire",
    skills: ["React", "Node.js", "TypeScript", "AWS"],
    experience: "5 years",
    education: "Master's in Computer Science",
    location: "San Francisco, CA"
  },
  {
    id: 2,
    candidateName: "Robert Smith",
    email: "robert.smith@example.com",
    phone: "+1 (555) 234-5678",
    appliedJob: "Product Manager",
    appliedDate: "2024-01-18",
    cvMatchPercent: 85,
    interviewStatus: "Scheduled",
    aiScore: 75,
    recommendation: "Review",
    skills: ["Product Strategy", "Agile", "User Research", "Roadmapping"],
    experience: "7 years",
    education: "MBA",
    location: "New York, NY"
  },
  {
    id: 3,
    candidateName: "Emily Chen",
    email: "emily.chen@example.com",
    phone: "+1 (555) 345-6789",
    appliedJob: "HR Specialist",
    appliedDate: "2024-01-20",
    cvMatchPercent: 78,
    interviewStatus: "Pending",
    aiScore: 62,
    recommendation: "Review",
    skills: ["Recruitment", "Employee Relations", "HR Policies", "Onboarding"],
    experience: "4 years",
    education: "Bachelor's in HR Management",
    location: "Chicago, IL"
  },
  {
    id: 4,
    candidateName: "David Lee",
    email: "david.lee@example.com",
    phone: "+1 (555) 456-7890",
    appliedJob: "Data Scientist",
    appliedDate: "2024-01-22",
    cvMatchPercent: 95,
    interviewStatus: "Completed",
    aiScore: 91,
    recommendation: "Strong Hire",
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow"],
    experience: "6 years",
    education: "PhD in Data Science",
    location: "Boston, MA"
  },
  {
    id: 5,
    candidateName: "Sophia Garcia",
    email: "sophia.garcia@example.com",
    phone: "+1 (555) 567-8901",
    appliedJob: "Software Engineer",
    appliedDate: "2024-01-25",
    cvMatchPercent: 65,
    interviewStatus: "Rejected",
    aiScore: 40,
    recommendation: "Reject",
    skills: ["Java", "Spring Boot", "MySQL"],
    experience: "2 years",
    education: "Bachelor's in Software Engineering",
    location: "Austin, TX"
  },
  {
    id: 6,
    candidateName: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "+1 (555) 678-9012",
    appliedJob: "Product Manager",
    appliedDate: "2024-01-28",
    cvMatchPercent: 80,
    interviewStatus: "Scheduled",
    aiScore: 70,
    recommendation: "Review",
    skills: ["Product Management", "JIRA", "Analytics", "Go-to-Market"],
    experience: "8 years",
    education: "Master's in Business Administration",
    location: "Seattle, WA"
  },
  {
    id: 7,
    candidateName: "Jessica Wilson",
    email: "jessica.wilson@example.com",
    phone: "+1 (555) 789-0123",
    appliedJob: "UX Designer",
    appliedDate: "2024-02-01",
    cvMatchPercent: 88,
    interviewStatus: "In Progress",
    aiScore: 82,
    recommendation: "Strong Hire",
    skills: ["Figma", "User Research", "Wireframing", "Prototyping"],
    experience: "5 years",
    education: "Bachelor's in Design",
    location: "Los Angeles, CA"
  },
  {
    id: 8,
    candidateName: "Daniel Martinez",
    email: "daniel.martinez@example.com",
    phone: "+1 (555) 890-1234",
    appliedJob: "DevOps Engineer",
    appliedDate: "2024-02-03",
    cvMatchPercent: 90,
    interviewStatus: "Pending",
    aiScore: 85,
    recommendation: "Strong Hire",
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD"],
    experience: "6 years",
    education: "Master's in Cloud Computing",
    location: "Denver, CO"
  }
];

export default candidatesData;