const interviewsData = [
  {
    id: 1,
    candidateId: 101,
    candidateName: "Alice Johnson",
    candidateEmail: "alice.johnson@example.com",
    jobTitle: "AI Product Manager",
    jobId: "JOB-AI-001",
    status: "Sent", // Sent, Completed, Pending, Expired, In Progress
    statusDate: "2024-08-12",
    deadline: "2024-08-15",
    interviewLink: "https://interview.ai/abc123",
    sentDate: "2024-08-10",
    completedDate: null,
    aiScore: 85,
    interviewType: "Voice",
    duration: "45 mins",
    progress: 100,
    responses: 12,
    totalQuestions: 12,
    interviewer: "AI System",
    department: "Product"
  },
  {
    id: 2,
    candidateId: 102,
    candidateName: "Bob Williams",
    candidateEmail: "bob.williams@example.com",
    jobTitle: "Data Scientist",
    jobId: "JOB-DS-002",
    status: "Completed",
    statusDate: "2024-08-08",
    deadline: "2024-08-10",
    interviewLink: "https://interview.ai/def456",
    sentDate: "2024-08-05",
    completedDate: "2024-08-08",
    aiScore: 92,
    interviewType: "Video",
    duration: "60 mins",
    progress: 100,
    responses: 15,
    totalQuestions: 15,
    interviewer: "AI System",
    department: "Data Science"
  },
  {
    id: 3,
    candidateId: 103,
    candidateName: "Charlie Davis",
    candidateEmail: "charlie.davis@example.com",
    jobTitle: "Software Engineer",
    jobId: "JOB-SE-003",
    status: "Pending",
    statusDate: "2024-08-15",
    deadline: "2024-08-20",
    interviewLink: "https://interview.ai/ghi789",
    sentDate: "2024-08-14",
    completedDate: null,
    aiScore: null,
    interviewType: "Voice",
    duration: "50 mins",
    progress: 30,
    responses: 5,
    totalQuestions: 15,
    interviewer: "AI System",
    department: "Engineering"
  },
  {
    id: 4,
    candidateId: 104,
    candidateName: "Diana Miller",
    candidateEmail: "diana.miller@example.com",
    jobTitle: "AI Product Manager",
    jobId: "JOB-AI-001",
    status: "Sent",
    statusDate: "2024-08-16",
    deadline: "2024-08-18",
    interviewLink: "https://interview.ai/jkl012",
    sentDate: "2024-08-15",
    completedDate: null,
    aiScore: null,
    interviewType: "Video",
    duration: "45 mins",
    progress: 0,
    responses: 0,
    totalQuestions: 12,
    interviewer: "AI System",
    department: "Product"
  },
  {
    id: 5,
    candidateId: 105,
    candidateName: "Eve Green",
    candidateEmail: "eve.green@example.com",
    jobTitle: "HR Specialist",
    jobId: "JOB-HR-004",
    status: "Expired",
    statusDate: "2024-08-01",
    deadline: "2024-08-01",
    interviewLink: "https://interview.ai/mno345",
    sentDate: "2024-07-25",
    completedDate: null,
    aiScore: null,
    interviewType: "Voice",
    duration: "40 mins",
    progress: 15,
    responses: 2,
    totalQuestions: 10,
    interviewer: "AI System",
    department: "Human Resources"
  },
  {
    id: 6,
    candidateId: 106,
    candidateName: "Frank Wilson",
    candidateEmail: "frank.wilson@example.com",
    jobTitle: "DevOps Engineer",
    jobId: "JOB-DE-005",
    status: "In Progress",
    statusDate: "2024-08-17",
    deadline: "2024-08-22",
    interviewLink: "https://interview.ai/pqr678",
    sentDate: "2024-08-16",
    completedDate: null,
    aiScore: null,
    interviewType: "Video",
    duration: "55 mins",
    progress: 65,
    responses: 8,
    totalQuestions: 12,
    interviewer: "AI System",
    department: "Engineering"
  },
  {
    id: 7,
    candidateId: 107,
    candidateName: "Grace Taylor",
    candidateEmail: "grace.taylor@example.com",
    jobTitle: "UX Designer",
    jobId: "JOB-UX-006",
    status: "Completed",
    statusDate: "2024-08-05",
    deadline: "2024-08-08",
    interviewLink: "https://interview.ai/stu901",
    sentDate: "2024-08-01",
    completedDate: "2024-08-05",
    aiScore: 88,
    interviewType: "Voice",
    duration: "50 mins",
    progress: 100,
    responses: 10,
    totalQuestions: 10,
    interviewer: "AI System",
    department: "Design"
  },
  {
    id: 8,
    candidateId: 108,
    candidateName: "Henry Brown",
    candidateEmail: "henry.brown@example.com",
    jobTitle: "Software Engineer",
    jobId: "JOB-SE-003",
    status: "Sent",
    statusDate: "2024-08-19",
    deadline: "2024-08-25",
    interviewLink: "https://interview.ai/vwx234",
    sentDate: "2024-08-18",
    completedDate: null,
    aiScore: null,
    interviewType: "Video",
    duration: "60 mins",
    progress: 0,
    responses: 0,
    totalQuestions: 18,
    interviewer: "AI System",
    department: "Engineering"
  }
];

export default interviewsData;